---
- name: Configure FireWall | Open port grafana
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
  when: firewall_enabled
  register: change_rules

- name: Configure FireWall | Restart firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: change_rules.changed
