---

- name: Copy rpm file Grafana
  copy:
     src: grafana-7.0.3-1.x86_64.rpm
     dest: /tmp/grafana-7.0.3-1.x86_64.rpm
  register: grafana_copy

- name: Install package Grafana
  yum:
     name: /tmp/grafana-7.0.3-1.x86_64.rpm
     state: present
  when: grafana_copy.changed
