---

- include: firewall.yml
  become: true
  when: ansible_os_family == 'RedHat'

- include: preflight.yml
  tags:
    - grafana_install
    - grafana_configure
    - grafana_notifications

- include: install.yml
  become: true
  tags:
    - grafana_install

- include: configure.yml
  become: true
  tags:
    - grafana_configure

- include: plugins.yml
  when: grafana_plugins != []
  tags:
    - grafana_configure

- name: Restart grafana before configuring datasources and dashboards
  meta: flush_handlers
  tags:
    - grafana_install
    - grafana_configure
    - grafana_notifications
    - grafana_run

- name: Wait for grafana to start (http/s)
  wait_for:
    host: "{{ grafana_address }}"
    port: "{{ grafana_port }}"
  when: grafana_server.protocol is undefined or grafana_server.protocol in ['http', 'https']
  tags:
    - grafana_install
    - grafana_configure
    - grafana_notifications
    - grafana_run
